#exec : main.o
#	gcc -o exec main.o
#main.o : 0110-fprintf.c
#	gcc -o main.o -c 0110-fprintf.c
#clean : rm exec main.o
#
include ./Makefile.config1
include ./Makefile.config2
include ./Makefile.common
include ./Makefile.rules
