#!/bin/bash

#TARGET_FILE= $1
KEYWORLD="recursive"
LASTLINT=""
while read -r line
do
        if [  "${line}"x != "${LASTLINT}"x ]; then
                echo "${line}"
                LASTLINT="${line}"
        fi
done < $1
